spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/grid07db
    username: grid07
    password: grid07pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

logging:
  level:
    com.grid07.assignment: INFO
